name: amitrafurniture
description: A furniture app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/google.png
    - assets/images/whatsapp.png
    - assets/images/Kursi.png
    - assets/images/Lemari.png
    - assets/images/laci meja.jpg
    - assets/images/kursigoyang.jpeg
    - assets/images/kursisantai.jpeg
    - assets/images/produk1.jpg
    - assets/images/produk2.jpg
    - assets/images/produk3.jpg
    - assets/images/produk4.jpg
    - assets/images/produk5.jpg
    - assets/images/produk6.jpg
    - assets/images/dan1.jpg
    - assets/images/dan2.jpg
    - assets/images/dan3.jpg
    - assets/images/dan4.jpg
    - assets/images/dan5.jpg
    - assets/images/dan6.jpg 
    - assets/images/dan7.jpg
    - assets/images/dan8.jpg
    - assets/images/ranjang minimalis.jpeg
    - assets/images/mejakerja.jpg
    - assets/images/kursikayujati.jpeg
    - assets/images/kursirotan.jpeg
    - assets/images/sofasantai.jpeg
